version: '3'

services:
  service:
    image: catalog-service:latest
    ports:
      - 8080:8080
    environment:
      - S_POSTGRES_HOST=postgres
      - S_POSTGRES_USER=postgres
      - S_POSTGRES_PASSWORD=postgres
      - S_POSTGRES_DB=postgres
      - S_KAFKA_BOOTSTRAP_HOST=kafka:9092
    depends_on:
      - kafka
      - postgres